path = "/home/arcos/.espressif"
idf_path = "/home/arcos/.espressif/v5.5/esp-idf"
esp_idf_json_path = "/home/arcos/.espressif/tools"
tool_download_folder_name = "/home/arcos/.espressif/dist"
tool_install_folder_name = "/home/arcos/.espressif/tools"
python_env_folder_name = "python_env"
target = ["all"]
idf_versions = ["v5.5"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://github.com"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = true
skip_prerequisites_check = false
idf_features = ["ci", "docs"]
