apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb3-core:8181
    database: iot_data
    user: ""
    password: ""
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: ""
      defaultBucket: iot_data
      maxSeries: 1000