[env:c6_temp_hum]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
  -DNODE_ID=1
  -DSENSOR_ROLE=1

[env:c6_lum]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
  -DNODE_ID=2
  -DSENSOR_ROLE=2

[env:c6_motion]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
  -DNODE_ID=3
  -DSENSOR_ROLE=3
